name: Workflow de exemplo.

on:
  push:

jobs:
  
  checkout_code:
    name: Faz checkout do codigo
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout repositorio
        uses: action/checkout@3.3.0
        
      - name: Upload a build Artifact
        uses: actions/upload-artifact@3.1.2
        with:
           name: ${{ vars.MODULO }}
           path: .
        
 
